### ISSUE TITLE
Investigate Cycle Diversity

### ISSUE THREAD

**Issue by WorldMaker** [WorldMaker/cycle-gear#1]
See if it makes sense to refactor this to use `xstream` instead of `Rx` or work more directly with Cycle's stream adapters.

**Comment by kristianmandrup** [comment]
Is it working with `xstream` yet!? I also wanted to add an extra abstraction level on top, more like Services that are pluggable like electrical outlets and plugs (streams = electricity, services = appliances (sinks) or "power sources" essentially).

**Comment by WorldMaker** [comment]
From what I've managed, it works fine with "Diversity" to the extent that you can adapt it and things will most just work, you just end up with an Rx dependency to bloat a project that doesn't already need it. On the other hand, the new "Cycle Unity" project that seems to be about finished moves almost all of the Cycle components to `xstream`, simplifies away most of the adapters, and probably means that this should be using `xstream` when that version arrives.

I think I would need a longer description of your proposed next abstraction level, to get a feel for what you are thinking. I've been leaning towards another direction, I think, trying to find ways to break up gears into even smaller pieces, but I haven't yet had the right insights into what those pieces might be or how they might fit together. For now I've been building increasingly complicated factories, and I'm waiting for the gestalt of what the higher order operations are to come to me.

**Comment by kristianmandrup** [comment]
Yes, Cycle Unified is the way to go, why xstream seems like the logical choice moving forward as well. I started working on a client side Service infrastructure with streams, IO adapters etc. but before I came to Cycle.js. Now I need to find a way to integrate Cycle/Gear concepts into my model.
I will likely try to draw something up on draw.io soon.
Would love to see you continue my work on gears to make it work with *Cycle Unified* and xstream.

Cheers!

**Comment by WorldMaker** [comment]
Published a first alpha build so I can experiment with it in my main project. I've got the downstream side of things adapted per Cycle Unified (which is easy because it's just an `adapt()` function to call, though I wish `adapt()` wasn't TS `any` typed, but that's something to bring up on the Cycle side and pushes the edges of TS' typing limits anyway). I haven't settled on an approach to handle Gears that aren't xstream backed yet, especially one that is relatively well typed, so this is probably *very* alpha for now.
